/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeEntity } from './typeEntity';
import { WorkoutEntityDateStart } from './workoutEntityDateStart';
import { ExerciseEntity } from './exerciseEntity';


export interface WorkoutDto { 
    name?: string;
    date_start?: WorkoutEntityDateStart;
    date_finish?: WorkoutEntityDateStart;
    duration?: number;
    type?: TypeEntity;
    exercises?: Array<ExerciseEntity>;
}

