/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkoutEntityDateStartNumberFormatCurrency } from './workoutEntityDateStartNumberFormatCurrency';


export interface WorkoutEntityDateStartNumberFormat { 
    groupingUsed?: boolean;
    parseIntegerOnly?: boolean;
    maximumIntegerDigits?: number;
    minimumIntegerDigits?: number;
    maximumFractionDigits?: number;
    minimumFractionDigits?: number;
    currency?: WorkoutEntityDateStartNumberFormatCurrency;
    roundingMode?: WorkoutEntityDateStartNumberFormat.RoundingModeEnum;
}
export namespace WorkoutEntityDateStartNumberFormat {
    export type RoundingModeEnum = 'UP' | 'DOWN' | 'CEILING' | 'FLOOR' | 'HALF_UP' | 'HALF_DOWN' | 'HALF_EVEN' | 'UNNECESSARY';
    export const RoundingModeEnum = {
        Up: 'UP' as RoundingModeEnum,
        Down: 'DOWN' as RoundingModeEnum,
        Ceiling: 'CEILING' as RoundingModeEnum,
        Floor: 'FLOOR' as RoundingModeEnum,
        HalfUp: 'HALF_UP' as RoundingModeEnum,
        HalfDown: 'HALF_DOWN' as RoundingModeEnum,
        HalfEven: 'HALF_EVEN' as RoundingModeEnum,
        Unnecessary: 'UNNECESSARY' as RoundingModeEnum
    };
}


