/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkoutEntityDateStartDateFormatSymbols { 
    eras?: Array<string>;
    months?: Array<string>;
    shortMonths?: Array<string>;
    weekdays?: Array<string>;
    shortWeekdays?: Array<string>;
    zoneStrings?: Array<Array<string>>;
    localPatternChars?: string;
    amPmStrings?: Array<string>;
}

